
export const searchcustomerCISLocators = (page) => ({
  buttonSearch: page.getByRole('button', { name: 'ค้นหา', exact: true }),
  policyInput: page.getByLabel('เลขที่กรมธรรม์'),
  checkdatagridPolicy: (policy) => page.getByRole('gridcell', { name: policy, exact: true }),
  customerdetailButton: page.getByRole('gridcell', { name: '' })
})

export const detailcustomerCISLocatorsArraykey = (page) => ({
SELECTOR_Panel5_1_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(0).locator('td').nth(0),
SELECTOR_Panel5_2_btn : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(0).locator('td').nth(1),
SELECTOR_Panel5_3_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(0).locator('td').nth(2),
SELECTOR_Panel5_4_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(0).locator('td').nth(3),
SELECTOR_Panel5_5_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(0).locator('td').nth(4),
SELECTOR_Panel5_6_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(0).locator('td').nth(5),
SELECTOR_Panel5_7_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(0).locator('td').nth(6),
SELECTOR_Panel5_8_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(0).locator('td').nth(7),
SELECTOR_Panel5_9_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(0).locator('td').nth(8),
SELECTOR_Panel5_10_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(0).locator('td').nth(9),
SELECTOR_Panel5_11_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(0).locator('td').nth(10),
SELECTOR_Panel5_12_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(0).locator('td').nth(11),
SELECTOR_Panel5_13_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(0).locator('td').nth(12),
SELECTOR_Panel5_14_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(0).locator('td').nth(13),
SELECTOR_Panel5_15_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(0).locator('td').nth(14),
SELECTOR_Panel5_16_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(0).locator('td').nth(15),
SELECTOR_Panel5_17_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(0).locator('td').nth(16),
SELECTOR_Panel5_18_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(0).locator('td').nth(17),
SELECTOR_Panel5_19_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(0).locator('td').nth(18),
SELECTOR_Panel5_20_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(0).locator('td').nth(19),
SELECTOR_Panel5_21_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(0).locator('td').nth(20),
SELECTOR_Panel5_22_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(0).locator('td').nth(21),
SELECTOR_Panel31_23_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(0).locator('td').nth(0),
SELECTOR_Panel31_24_btn : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(0).locator('td').nth(1),
SELECTOR_Panel31_25_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(1).locator('td').nth(0),
SELECTOR_Panel31_26_btn : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(1).locator('td').nth(1),
SELECTOR_Panel31_27_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(2).locator('td').nth(0),
SELECTOR_Panel31_28_btn : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(2).locator('td').nth(1),
SELECTOR_Panel31_29_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(3).locator('td').nth(0),
SELECTOR_Panel31_30_btn : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(3).locator('td').nth(1),
SELECTOR_Panel31_31_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(4).locator('td').nth(0),
SELECTOR_Panel31_32_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(4).locator('td').nth(1),
SELECTOR_Panel31_33_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(5).locator('td').nth(0),
SELECTOR_Panel31_34_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(5).locator('td').nth(1),
SELECTOR_Panel31_35_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(6).locator('td').nth(0),
SELECTOR_Panel31_36_btn : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(6).locator('td').nth(1),
SELECTOR_Panel32_37_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(0).locator('td').nth(0),
SELECTOR_Panel32_38_btn : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(0).locator('td').nth(1),
SELECTOR_Panel32_39_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(1).locator('td').nth(0),
SELECTOR_Panel32_40_btn : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(1).locator('td').nth(1),
SELECTOR_Panel32_41_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(2).locator('td').nth(0),
SELECTOR_Panel32_42_btn : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(2).locator('td').nth(1),
SELECTOR_Panel32_43_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(3).locator('td').nth(0),
SELECTOR_Panel32_44_btn : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(3).locator('td').nth(1),
SELECTOR_Panel32_45_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(4).locator('td').nth(0),
SELECTOR_Panel32_46_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(4).locator('td').nth(1),
SELECTOR_Panel32_47_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(5).locator('td').nth(0),
SELECTOR_Panel32_48_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(5).locator('td').nth(1),
SELECTOR_Panel32_49_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(6).locator('td').nth(0),
SELECTOR_Panel32_50_btn : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(6).locator('td').nth(1),
SELECTOR_Panel33_51_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(0).locator('td').nth(0),
SELECTOR_Panel33_52_btn : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(0).locator('td').nth(1),
SELECTOR_Panel33_53_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(1).locator('td').nth(0),
SELECTOR_Panel33_54_btn : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(1).locator('td').nth(1),
SELECTOR_Panel33_55_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(2).locator('td').nth(0),
SELECTOR_Panel33_56_btn : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(2).locator('td').nth(1),
SELECTOR_Panel33_57_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(3).locator('td').nth(0),
SELECTOR_Panel33_58_btn : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(3).locator('td').nth(1),
SELECTOR_Panel33_59_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(4).locator('td').nth(0),
SELECTOR_Panel33_60_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(4).locator('td').nth(1),
SELECTOR_Panel33_61_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(5).locator('td').nth(0),
SELECTOR_Panel33_62_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(5).locator('td').nth(1),
SELECTOR_Panel33_63_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(6).locator('td').nth(0),
SELECTOR_Panel33_64_btn : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(6).locator('td').nth(1),
SELECTOR_Panel34_65_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(0).locator('td').nth(0),
SELECTOR_Panel34_66_btn : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(0).locator('td').nth(1),
SELECTOR_Panel34_67_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(1).locator('td').nth(0),
SELECTOR_Panel34_68_btn : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(1).locator('td').nth(1),
SELECTOR_Panel34_69_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(2).locator('td').nth(0),
SELECTOR_Panel34_70_btn : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(2).locator('td').nth(1),
SELECTOR_Panel34_71_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(3).locator('td').nth(0),
SELECTOR_Panel34_72_btn : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(3).locator('td').nth(1),
SELECTOR_Panel34_73_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(4).locator('td').nth(0),
SELECTOR_Panel34_74_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(4).locator('td').nth(1),
SELECTOR_Panel34_75_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(5).locator('td').nth(0),
SELECTOR_Panel34_76_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(5).locator('td').nth(1),
SELECTOR_Panel34_77_text : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(6).locator('td').nth(0),
SELECTOR_Panel34_78_btn : page => page.locator('table').nth(0).locator('tbody').nth(0).locator('tr').nth(6).locator('td').nth(1),
})