// Selector.js
// รวม Selector และข้อมูลเมนูที่ใช้ในเทสต์ทั้งหมด

module.exports = {
  usernameInput: '#username',
  passwordInput: '#password',
  loginButton: 'button[name="loginButton"]',
  body: 'body',
  // เพิ่ม selector อื่นๆ ตามที่ใช้ในไฟล์ TS_EMAILNOTI


  // ตัวอย่าง selector ที่ใช้กับ cy.get('input#' + monthInputId) และ yearInputId
  monthInput: (id) => `input#${id}`,
  yearInput: (id) => `input#${id}`,


  // ตัวอย่าง selector ที่ใช้กับ cy.get('span.' + spanClassBtn)
  spanClass: (className) => `span.${className}`,


  // Selector สำหรับปุ่มและ element ที่ใช้บ่อย (จากทั้งสองไฟล์)
  BTN_CLEAR: "span.MuiButton-label:contains('ล้างเงื่อนไข')",
  BTN_SEARCH: "span.MuiButton-label:contains('ค้นหา')",
  BTN_SEARCH_FORM: "[id='tab/inquiry/search/main'] > div > div > div:nth-child(2) > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > form > div > div > div > div > div > div > div > div > div.MuiGrid-root.OLIColumnLayout-basicActionComponent-487.basicActionComponent.MuiGrid-item.MuiGrid-grid-xs-auto.MuiGrid-grid-sm-12 > div > div:nth-child(2) > button > span.MuiButton-label",
  TOOLBAR_RESULT: "span.Toolbar-Message-text, span.Toolbar-Message-value",
  DETAIL_TEXT: "div,table",
  DETAIL_FIELDS: [
    { selector: "label:contains('รายละเอียด') + div, label:contains('Detail') + div", label: 'รายละเอียด' },
    { selector: "input[name='detail'], textarea[name='detail']", label: 'ช่องรายละเอียด' }
  ],

  // เพิ่มจาก Reuseable/Selector.js
  policyNoInput: 'input[name="policyNo"], input[id*="policy"], input[aria-label*="เลขที่กรมธรรม์"]',
  insuredFirstNameInput: 'input[name*="firstName"], input[id*="firstName"], input[aria-label*="ชื่อ"]',
  insuredLastNameInput: 'input[name*="lastName"], input[id*="lastName"], input[aria-label*="นามสกุล"]',
  cardNoInput: 'input[name*="card"], input[id*="card"], input[aria-label*="บัตร"]',

  // เมนูหลัก
  SERVICE_MENU: {
    label: 'ระบบงานให้บริการ',
    href: '#menu-item-3000',
    class: 'yui3-menu-label yui3-menu-label-active',
  },
  EMAIL_NOTIFICATION_MENU: {
    label: 'ระบบ Email Notification',
  },
  EMN_SUB_MENU_1: {
    label: 'ระบบออกจดหมาย',
    spanClass: 'MuiButton-label',
    selector: '#root > div > div > div.MuiToolbar-root.MuiToolbar-regular.AppLayout-toolbarPrimaryNav-31 > div > div:nth-child(2) > span:nth-child(1) > button'
  },
  EMN_SUB_MENU_1_1: {
    label: 'รายงานสรุปการออกจดหมาย',
  },
  EMN_SUB_MENU_1_1_BTN_1: {
    label: 'ค้นหา',
    spanClass: 'MuiButton-label',
  },
  EMN_SUB_MENU_1_1_LIST_1: {
    label: 'เดือน',
    inputId: 'letterMM',
    placeholderClass: 'css-jb3yj5-placeholder',
    wrapperClass: 'css-tntsk8',
  },
  EMN_SUB_MENU_1_1_LIST_2: {
    label: 'ปี พ.ศ.',
    inputId: 'letterYYYY',
    placeholderClass: 'css-jb3yj5-placeholder',
    wrapperClass: 'css-tntsk8',
  },
  // --- NBS Portal  ---
  NBS_PORTAL_MENU_Navigate_1: {
    label: 'ระบบงาน NBS Portal',
    href: '#menu-item-98000',
  },
  HOME_SUB_MENU_Navigate_2: {
    label: 'Home',
    href: '/nbsweb/secure/msa/nbsportal/index.html',
    role: 'menuitem',
  },

  // --- Automatic Alteration  ---
  SELECTOR_ALTERNATION_MENU: {
    label: 'ระบบงานสำหรับรับเรื่องและพิจารณาสลักหลังกรมธรรม์',
    href: '/thaisamut/web/alter/index.html',
  },
  SELECTOR_ALTERNATION_MENU_SUB_1: {
    label: 'ค้นหาใบสอบถาม',
    selector: '<span class="MuiButton-label">ค้นหาใบสอบถาม</span>',
  },
  SELECTOR_Automatic_Alteration_SEARCH_1: 'input[name="inquiryDateFrom"][placeholder="เริ่มต้น"][type="text"].MuiInputBase-input.MuiInput-input.MuiInputBase-inputAdornedEnd',
  SELECTOR_Automatic_Alteration_SEARCH_2: 'input[name="inquiryDateTo"][placeholder="สิ้นสุด"][type="text"].MuiInputBase-input.MuiInput-input.MuiInputBase-inputAdornedEnd',
  SELECTOR_Automatic_Alteration_SEARCH_3: 'input[type="text"].MuiInputBase-input.MuiInput-input[value^="__-"]',
  SELECTOR_Automatic_Alteration_SEARCH_4: '#branchSourceCode > div > div > div > div',
  SELECTOR_Automatic_Alteration_SEARCH_5: '#serviceCode > div > div > div > div',
  SELECTOR_Automatic_Alteration_SEARCH_6: '#inquiryStatus > div > div > div > div',
  SELECTOR_Automatic_Alteration_SEARCH_7: '#tab\\/inquiry\\/search\\/main > div > div > div:nth-child(2) > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > form > div > div > div > div > div > div > div > div > div:nth-child(9) > div > div > input',
  SELECTOR_Automatic_Alteration_SEARCH_8: '#tab\\/inquiry\\/search\\/main > div > div > div:nth-child(2) > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > form > div > div > div > div > div > div > div > div > div:nth-child(10) > div > div > input',
  SELECTOR_Automatic_Alteration_SEARCH_9: '#tab\\/inquiry\\/search\\/main > div > div > div:nth-child(2) > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > form > div > div > div > div > div > div > div > div > div:nth-child(11) > div > div > input',
  SELECTOR_Automatic_Alteration_SEARCH_10: '#tab\\/inquiry\\/search\\/main > div > div > div:nth-child(2) > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > form > div > div > div > div > div > div > div > div > div:nth-child(12) > div > div > input',

  // --- CIS ---
  // หน้าเมนูหลัก CIS ค้นหาลูกค้า
  SELECTOR_CIS_MENU_SUB_1_Navigate_1_Menu_Bar_Label: 'a[href="#menu-item-2000"].yui3-menu-label',
  SELECTOR_CIS_MENU_SUB_1_Navigate_2_Menu_Bar_Label: 'a[href="#menu-item-1800"].yui3-menu-label',
  SELECTOR_CIS_MENU_SUB_1_Navigate_3_Menu_Bar_Label: 'a.yui3-menuitem-content[role="menuitem"][href^="/nbsweb/secure/remoteaction/cisapp/react/index.html"]',

  // CIS Customer Search Page (new selectors)
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_In_Page_1_Menu_Bar_Label: 'p.MuiTypography-root.MuiTypography-body1.MuiTypography-colorPrimary[style*="font-weight: bold;"]:contains("ค้นหาข้อมูล")',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_In_Page_2_Input_Text: '#cardId',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_In_Page_3_Input_Text: '#customerName',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_In_Page_4_Input_Text: '#customerLastName',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_In_Page_5_Input_Text: '#tel',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_In_Page_6_Input_Text: '#policyNo',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_In_Page_7_Head_Column_Data_Grid: 'div.MUIDataTableHeadCell-data-47:contains("ดูข้อมูล")',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_In_Page_8_Head_Column_Data_Grid: 'div.MUIDataTableHeadCell-data-47:contains("ประเภทบัตร / หมายเลขบัตร")',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_In_Page_9_Head_Column_Data_Grid: 'div.MUIDataTableHeadCell-data-47:contains("เลขที่กรมธรรม์")',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_In_Page_10_Head_Column_Data_Grid: 'div.MUIDataTableHeadCell-data-47:contains("ชื่อ - นามสกุล")',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_In_Page_11_Head_Column_Data_Grid: 'div.MUIDataTableHeadCell-data-47:contains("ความสัมพันธ์กับกรมธรรม์")',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_In_Page_12_Head_Column_Data_Grid: 'div.MUIDataTableHeadCell-data-47:contains("วัน / เดือน / ปีเกิด")',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_In_Page_13_Head_Column_Data_Grid: 'div.MUIDataTableHeadCell-data-47:contains("หมายเลขโทรศัพท์")',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_In_Page_14_Head_Column_Data_Grid: 'div.MUIDataTableHeadCell-data-47:contains("สถานะลูกค้า")',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_In_Page_15_Button: 'span.MuiButton-label:contains("ล้างเงื่อนไข")',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_In_Page_16_Button: 'button.MuiButtonBase-root.MuiButton-root.MuiButton-contained.MuiButton-containedPrimary[type="button"]',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_In_Page_17_Button: 'span.MuiButton-label.MuiButton-label:contains("สร้าง Case")',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_In_Page_18_Menu_Bar_Label: '#tab\\/cisapp_customer\\/search > div > div > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-true > div > div > div.MuiToolbar-root.MuiToolbar-regular.MUIDataTableToolbar-root-52.MuiToolbar-gutters > div.MUIDataTableToolbar-left-53 > span > span:nth-child(4)',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_In_Page_19_Button: '#MUIDataTableBodyRow-0 > td:nth-child(2) > button',

  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_In_Page_20_Data_Grid: '#MUIDataTableBodyRow-0 > td:nth-child(4) > div > div:nth-child(1) > i',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_In_Page_21_Data_Grid: '#MUIDataTableBodyRow-0 > td:nth-child(4) > div > div:nth-child(2) > p',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_In_Page_22_Data_Grid: '#MUIDataTableBodyRow-0 > td:nth-child(6)',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_In_Page_23_Data_Grid: '#MUIDataTableBodyRow-0 > td:nth-child(8) > div > div:nth-child(1) > i',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_In_Page_24_Data_Grid: '#MUIDataTableBodyRow-0 > td:nth-child(8) > div > div:nth-child(2) > p',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_In_Page_25_Data_Grid: '#MUIDataTableBodyRow-0 > td:nth-child(10)',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_In_Page_26_Data_Grid: '#MUIDataTableBodyRow-0 > td:nth-child(12) > span > div > div:nth-child(1) > p',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_In_Page_27_Data_Grid: '#MUIDataTableBodyRow-0 > td:nth-child(14) > p',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_In_Page_28_Data_Grid: '#MUIDataTableBodyRow-0 > td:nth-child(16) > p',

  //CIS หน้าจอค้นหาข้อมูลลูกค้า > ดูรายละเอียด  CIS_MENU_SUB_1_SEARCH_1_Detail_1
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_In_Page_1_Menu_Bar_Label: '#root > header > div > div:nth-child(1) > ul:nth-child(2)',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_In_Page_2_Menu_Bar_Label: '#menu-list > ul:nth-child(2) > li',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_In_Page_3_Menu_Bar_Label: '#menu-list > ul:nth-child(3) > li',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_In_Page_4_Menu_Bar_Label: '#menu-list > ul:nth-child(4) > li',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_In_Page_5_Menu_Bar_Label: '#menu-list > ul:nth-child(5)',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_In_Page_6_Menu_Bar_Label: '#menu-list > ul:nth-child(7) > li',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_In_Page_7_Menu_Bar_Label: '#menu-list > ul:nth-child(8) > li',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_In_Page_8_Menu_Bar_Label: '#menu-list > ul:nth-child(9) > li',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_In_Page_9_Menu_Bar_Label: '#menu-list > ul:nth-child(10) > li',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_In_Page_10_Menu_Bar_Label: '#menu-list > ul:nth-child(11) > li',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_In_Page_11_Detail_Panel: page => page.locator('#root > header > div > div:nth-child(3) > ul:nth-child(3) > li'),

  // CIS หน้าจอค้นหาข้อมูลลูกค้า > ดูรายละเอียด > panel ข้อมูลส่วนตัว
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_1_Header_Panel: '#section-cust-detail > div > div.MuiButtonBase-root.MuiExpansionPanelSummary-root.makeStyles-root-48.uncollapsible.Mui-expanded > div > div > div.MuiGrid-root.ExpansionPanelSummaryTitle.MuiGrid-item',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_2_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(1) > div > div:nth-child(2) > div > div > div > div:nth-child(1) > div > div > p',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_3_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(1) > div > div:nth-child(2) > div > div > div > div:nth-child(2) > div > div > span > div > div:nth-child(1) > i',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_4_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(1) > div > div:nth-child(2) > div > div > div > div:nth-child(2) > div > div > span > div > div:nth-child(2) > p',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_5_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(1) > div > div:nth-child(2) > div > div > div > div:nth-child(2) > div > div > span > i',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_6_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(1) > div > div:nth-child(2) > div > div > div > div:nth-child(2) > div > div > span > p',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_7_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(1) > div > div:nth-child(2) > div > div > div > div:nth-child(3) > div > div:nth-child(1) > p',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_8_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(1) > div > div:nth-child(2) > div > div > div > div:nth-child(4) > div > div:nth-child(1) > p',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_9_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(1) > div > div:nth-child(2) > div > div > div > div:nth-child(5) > div > div > div > div:nth-child(1) > i',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_10_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(1) > div > div:nth-child(2) > div > div > div > div:nth-child(5) > div > div > div > div:nth-child(2) > p',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_11_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(1) > div > div:nth-child(2) > div > div > div > div:nth-child(6) > p',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_12_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div > div:nth-child(2) > div:nth-child(1) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-4 > p',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_13_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div > div:nth-child(2) > div:nth-child(1) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-8 > div > div > div:nth-child(1) > p',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_14_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div > div:nth-child(2) > div:nth-child(1) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-8 > div > div > div:nth-child(2) > p',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_15_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div > div:nth-child(2) > div:nth-child(2) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-4 > p',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_16_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div > div:nth-child(2) > div:nth-child(2) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-8 > div > p',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_17_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div > div:nth-child(2) > div:nth-child(3) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-4 > p',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_18_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div > div:nth-child(2) > div:nth-child(3) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-8 > div > p',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_19_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div > div:nth-child(2) > div:nth-child(4) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-4 > p',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_20_Detail_Panel: 'p.MuiTypography-root.MuiTypography-body1:contains("ลูกค้าเป็นสมาชิก Ocean Club")',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_21_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div > div.MuiGrid-root.makeStyles-mainColumn-206.makeStyles-mainColumnBorder-207.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-6 > div:nth-child(1) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-8 > div > a',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_22_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div > div.MuiGrid-root.makeStyles-mainColumn-206.makeStyles-mainColumnBorder-207.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-6 > div:nth-child(2) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-4 > p',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_23_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div > div.MuiGrid-root.makeStyles-mainColumn-206.makeStyles-mainColumnBorder-207.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-6 > div:nth-child(2) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-8 > div > p',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_24_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div > div.MuiGrid-root.makeStyles-mainColumn-206.makeStyles-mainColumnBorder-207.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-6 > div:nth-child(3) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-4 > p',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_25_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div > div.MuiGrid-root.makeStyles-mainColumn-206.makeStyles-mainColumnBorder-207.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-6 > div:nth-child(3) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-8 > div > p',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_26_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div > div.MuiGrid-root.makeStyles-mainColumn-206.makeStyles-mainColumnBorder-207.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-6 > div:nth-child(4) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-4 > p',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_27_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div > div.MuiGrid-root.makeStyles-mainColumn-206.makeStyles-mainColumnBorder-207.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-6 > div:nth-child(4) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-8 > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_28_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div > div.MuiGrid-root.makeStyles-mainColumn-206.makeStyles-mainColumnBorder-207.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-6 > div:nth-child(5) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-4 > p',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_29_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div > div.MuiGrid-root.makeStyles-mainColumn-206.makeStyles-mainColumnBorder-207.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-6 > div:nth-child(5) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-8 > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_30_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div > div.MuiGrid-root.makeStyles-mainColumn-206.makeStyles-mainColumnBorder-207.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-6 > div:nth-child(6) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-4 > p',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_31_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div > div.MuiGrid-root.makeStyles-mainColumn-206.makeStyles-mainColumnBorder-207.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-6 > div:nth-child(6) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-8 > div > p',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_32_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div > div.MuiGrid-root.makeStyles-mainColumn-206.makeStyles-mainColumnBorder-207.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-6 > div:nth-child(7) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-4 > p',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_33_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div > div.MuiGrid-root.makeStyles-mainColumn-206.makeStyles-mainColumnBorder-207.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-6 > div:nth-child(7) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-8 > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_34_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div > div.MuiGrid-root.makeStyles-mainColumn-206.makeStyles-mainColumnBorder-207.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-6 > div:nth-child(8) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-4 > p',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_35_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div > div.MuiGrid-root.makeStyles-mainColumn-206.makeStyles-mainColumnBorder-207.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-6 > div:nth-child(8) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-8 > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_36_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div > div.MuiGrid-root.makeStyles-mainColumn-206.makeStyles-mainColumnBorder-207.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-6 > div:nth-child(9) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-4 > p',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_37_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div > div.MuiGrid-root.makeStyles-mainColumn-206.makeStyles-mainColumnBorder-207.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-6 > div:nth-child(9) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-8 > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_38_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div > div.MuiGrid-root.makeStyles-mainColumn-206.makeStyles-mainColumnBorder-207.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-6 > div:nth-child(10) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-4 > p',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_39_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div > div.MuiGrid-root.makeStyles-mainColumn-206.makeStyles-mainColumnBorder-207.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-6 > div:nth-child(10) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-8 > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_40_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div > div.MuiGrid-root.makeStyles-mainColumn-206.makeStyles-mainColumnBorder-207.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-6 > div:nth-child(11) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-4 > p',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_1_In_Page_41_Detail_Panel: '#section-cust-detail > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div > div.MuiGrid-root.makeStyles-mainColumn-206.makeStyles-mainColumnBorder-207.MuiGrid-item.MuiGrid-grid-xs-12.MuiGrid-grid-sm-6 > div:nth-child(11) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-8 > div > p',

  // CIS หน้าจอค้นหาข้อมูลลูกค้า > ดูรายละเอียด > panel ข้อมูลที่อยู่
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_2_In_Page_1_Header_Panel: '#section-cust-address > div > div.MuiButtonBase-root.MuiExpansionPanelSummary-root.makeStyles-root-48.uncollapsible.Mui-expanded > div > div > div.MuiGrid-root.ExpansionPanelSummaryTitle.MuiGrid-item',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_2_In_Page_2_Button: '#section-cust-address > div > div.MuiButtonBase-root.MuiExpansionPanelSummary-root.makeStyles-root-48.uncollapsible.Mui-expanded > div > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-true > div > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_2_In_Page_3_Head_Column_Data_Grid: '#section-cust-address > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(1)',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_2_In_Page_4_Data_Grid: '#MUIDataTableBodyRow-0 > td:nth-child(2)',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_2_In_Page_5_Data_Grid: '#MUIDataTableBodyRow-1 > td:nth-child(2) > p',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_2_In_Page_6_Head_Column_Data_Grid: '#section-cust-address > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(2)',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_2_In_Page_7_Data_Grid: '#MUIDataTableBodyRow-0 > td:nth-child(4) > p',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_2_In_Page_8_Data_Grid: '#MUIDataTableBodyRow-1 > td:nth-child(4) > p',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_2_In_Page_9_Head_Column_Data_Grid: '#section-cust-address > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(3)',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_2_In_Page_10_Data_Grid: '#MUIDataTableBodyRow-0 > td:nth-child(6) > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_2_In_Page_11_Data_Grid: '#MUIDataTableBodyRow-1 > td:nth-child(6) > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_2_In_Page_12_Head_Column_Data_Grid: '#section-cust-address > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(4)',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_2_In_Page_13_Data_Grid: '#MUIDataTableBodyRow-0 > td:nth-child(8)',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_2_In_Page_14_Data_Grid: '#MUIDataTableBodyRow-1 > td:nth-child(8)',

  // CIS หน้าจอค้นหาข้อมูลลูกค้า > ดูรายละเอียด > panel ข้อมูลที่ติดต่อ
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_3_In_Page_1_Header_Panel: '#tab\\/cisapp_customer\\/display > div > div > div > div:nth-child(2) > div > div:nth-child(1) > div:nth-child(4) > :nth-child(1) > .MuiExpansionPanel-root > .MuiExpansionPanelSummary-root > .MuiExpansionPanelSummary-content > :nth-child(1) > .ExpansionPanelSummaryTitle',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_3_In_Page_2_Button: '#tab\\/cisapp_customer\\/display > div > div > div > div:nth-child(2) > div > div:nth-child(1) > div:nth-child(4) button > span.MuiButton-label',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_3_In_Page_3_Head_Column_Data_Grid: '#tab\\/cisapp_customer\\/display > div > div > div > div:nth-child(2) > div > div:nth-child(1) > div:nth-child(4) > div > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(1) > span > div.MUIDataTableHeadCell-data-47',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_3_In_Page_4_Data_Grid: '#MUIDataTableBodyRow-0 > td:nth-child(2) > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_3_In_Page_5_Head_Column_Data_Grid: '#tab\\/cisapp_customer\\/display > div > div > div > div:nth-child(2) > div > div:nth-child(1) > div:nth-child(4) > div > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(2) > span > div.MUIDataTableHeadCell-data-47',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_3_In_Page_6_Data_Grid: '#MUIDataTableBodyRow-0 > td:nth-child(4) > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_3_In_Page_7_Head_Column_Data_Grid: '#tab\\/cisapp_customer\\/display > div > div > div > div:nth-child(2) > div > div:nth-child(1) > div:nth-child(4) > div > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(3) > span > div.MUIDataTableHeadCell-data-47',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_3_In_Page_8_Data_Grid: '#MUIDataTableBodyRow-0 > td:nth-child(6) > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_3_In_Page_9_Head_Column_Data_Grid: '#tab\\/cisapp_customer\\/display > div > div > div > div:nth-child(2) > div > div:nth-child(1) > div:nth-child(4) > div > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(4) > span > div.MUIDataTableHeadCell-data-47',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_3_In_Page_10_Data_Grid: '#MUIDataTableBodyRow-0 > td:nth-child(8)',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_3_In_Page_11_Head_Column_Data_Grid: '#tab\\/cisapp_customer\\/display > div > div > div > div:nth-child(2) > div > div:nth-child(1) > div:nth-child(4) > div > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(5) > span > div.MUIDataTableHeadCell-data-47',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_3_In_Page_12_Data_Grid: '#MUIDataTableBodyRow-0 > td:nth-child(10) > div',

 
  // CIS หน้าจอค้นหาข้อมูลลูกค้า > ดูรายละเอียด > panel ข้อมูลครอบครัว
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_4_In_Page_1_Header_Panel: '#tab\\/cisapp_customer\\/display > div > div > div > div:nth-child(2) > div > div:nth-child(1) > div:nth-child(5) > div > div.MuiButtonBase-root.MuiExpansionPanelSummary-root.makeStyles-root-48 > div.MuiExpansionPanelSummary-content > div > div.MuiGrid-root.ExpansionPanelSummaryTitle.MuiGrid-item',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_4_In_Page_2_Head_Column_Data_Grid: '#tab\\/cisapp_customer\\/display > div > div > div > div:nth-child(2) > div > div:nth-child(1) > div:nth-child(5) > div > div.MuiCollapse-container > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(1) > span > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_4_In_Page_3_Head_Column_Data_Grid: '#tab\\/cisapp_customer\\/display > div > div > div > div:nth-child(2) > div > div:nth-child(1) > div:nth-child(5) > div > div.MuiCollapse-container > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(2) > span > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_4_In_Page_4_Head_Column_Data_Grid: '#tab\\/cisapp_customer\\/display > div > div > div > div:nth-child(2) > div > div:nth-child(1) > div:nth-child(5) > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(3) > span > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_4_In_Page_5_Head_Column_Data_Grid: '#tab\\/cisapp_customer\\/display > div > div > div > div:nth-child(2) > div > div:nth-child(1) > div:nth-child(5) > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(4) > span > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_4_In_Page_6_Head_Column_Data_Grid: '#tab\\/cisapp_customer\\/display > div > div > div > div:nth-child(2) > div > div:nth-child(1) > div:nth-child(5) > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(5) > span > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_4_In_Page_7_Head_Column_Data_Grid: '#tab\\/cisapp_customer\\/display > div > div > div > div:nth-child(2) > div > div:nth-child(1) > div:nth-child(5) > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(6) > span > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_4_In_Page_8_Head_Column_Data_Grid: '#tab\\/cisapp_customer\\/display > div > div > div > div:nth-child(2) > div > div:nth-child(1) > div:nth-child(5) > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(7) > span > div',

  // CIS หน้าจอค้นหาข้อมูลลูกค้า > ดูรายละเอียด > panel ประวัติการพิจารณาสินไหม
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_5_In_Page_1_Header_Panel: '#section-claim > div > div.MuiButtonBase-root.MuiExpansionPanelSummary-root.makeStyles-root-48 > div.MuiExpansionPanelSummary-content > div > div.MuiGrid-root.ExpansionPanelSummaryTitle.MuiGrid-item',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_5_In_Page_2_Head_Column_Data_Grid: 'div.MUIDataTableHeadCell-data-47:contains("เลขที่กรมธรรม์")',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_5_In_Page_3_Head_Column_Data_Grid: 'div.MUIDataTableHeadCell-data-47:contains("วันที่สินไหมรับเรื่อง")',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_5_In_Page_4_Head_Column_Data_Grid: '#section-claim > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(3) > span > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_5_In_Page_5_Head_Column_Data_Grid: '#section-claim > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(4) > span > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_5_In_Page_6_Head_Column_Data_Grid: '#section-claim > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(5) > span > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_5_In_Page_7_Head_Column_Data_Grid: '#section-claim > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(6) > span > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_5_In_Page_8_Head_Column_Data_Grid: '#section-claim > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(7) > span > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_5_In_Page_9_Head_Column_Data_Grid: '#section-claim > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(8) > span > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_5_In_Page_10_Head_Column_Data_Grid: '#section-claim > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(9) > span > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_5_In_Page_11_Head_Column_Data_Grid: '#section-claim > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(10)> span > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_5_In_Page_12_Head_Column_Data_Grid: '#section-claim > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(11) > span > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_5_In_Page_13_Head_Column_Data_Grid: '#section-claim > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(12) > span > div',

  // CIS หน้าจอค้นหาข้อมูลลูกค้า > ดูรายละเอียด > panel ประวัติการรับเรื่องสินไหม (panel_6)
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_6_In_Page_1_Header_Panel: '#tab\\/cisapp_customer\\/display > div > div > div > div:nth-child(2) > div > div:nth-child(2) > div:nth-child(2) > div > div > div:nth-child(1) > div > div > div:nth-child(2)',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_6_In_Page_2_Detail_Panel: '#section-payment-history-undefined > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(1) > span > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_6_In_Page_4_Detail_Panel: '#section-payment-history-undefined > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(2) > span > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_6_In_Page_6_Detail_Panel: '#section-payment-history-undefined > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(3) > span > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_6_In_Page_8_Detail_Panel: '#section-payment-history-undefined > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(5) > span > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_6_In_Page_10_Detail_Panel: '#section-payment-history-undefined > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(5) > span > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_6_In_Page_12_Detail_Panel: '#section-payment-history-undefined > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(6) > span > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_6_In_Page_14_Detail_Panel: '#section-payment-history-undefined > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(7) > span > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_6_In_Page_16_Detail_Panel: '#section-payment-history-undefined > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(8) > span > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_6_In_Page_18_Detail_Panel: '#section-payment-history-undefined > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(9) > span > div',

  // CIS หน้าจอค้นหาข้อมูลลูกค้า > ดูรายละเอียด > panel ประวัติการพิจารณาสินไหม
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_7_In_Page_1_Header_Panel: 'div.MuiGrid-root.MuiGrid-container.MuiGrid-direction-xs-column.MuiGrid-wrap-xs-nowrap.MuiGrid-align-content-xs-flex-start > div:nth-child(3) > div.makeStyles-setScroll-131 > div > div> div> div> div:nth-child(2)',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_7_In_Page_2_Head_Column_Data_Grid: '#section-payment-history-undefined > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(1) > span > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_7_In_Page_3_Head_Column_Data_Grid: '#section-payment-history-undefined > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(2) > span > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_7_In_Page_4_Head_Column_Data_Grid: '#section-payment-history-undefined > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(3) > span > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_7_In_Page_5_Head_Column_Data_Grid: '#section-payment-history-undefined > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(4) > span > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_7_In_Page_6_Head_Column_Data_Grid: '#section-payment-history-undefined > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(5) > span > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_7_In_Page_7_Head_Column_Data_Grid: '#section-payment-history-undefined > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(6) > span > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_7_In_Page_8_Head_Column_Data_Grid: '#section-payment-history-undefined > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(7) > span > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_7_In_Page_9_Head_Column_Data_Grid: '#section-payment-history-undefined > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(8) > span > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_7_In_Page_10_Head_Column_Data_Grid: '#section-payment-history-undefined > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(9) > span > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_7_In_Page_11_Head_Column_Data_Grid: '#section-payment-history-undefined > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(10) > span > div',
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_7_In_Page_12_Head_Column_Data_Grid: '#section-payment-history-undefined > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(11) > span > div',

  // CIS หน้าจอค้นหาข้อมูลลูกค้า > ดูรายละเอียด > panel รายละเอียดกรมธรรม์
  // Panel 8 selectors as dynamic functions
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_8_In_Page_1_Header_Panel: (policyNo) => `#section-policy-detail-${policyNo} > .MuiPaper-root > .MuiButtonBase-root > .MuiExpansionPanelSummary-content > :nth-child(1) > .ExpansionPanelSummaryTitle`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_8_In_Page_2_Detail_Panel: (policyNo) => `#section-policy-detail-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div:nth-child(1) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-4 > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_8_In_Page_3_Detail_Panel_Data: (policyNo) => `#section-policy-detail-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div:nth-child(1) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-8 > div > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_8_In_Page_4_Detail_Panel: (policyNo) => `#section-policy-detail-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div:nth-child(2) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-4 > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_8_In_Page_5_Detail_Panel_Data: (policyNo) => `#section-policy-detail-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div:nth-child(2) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-8 > div > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_8_In_Page_6_Detail_Panel: (policyNo) => `#section-policy-detail-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div:nth-child(3) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-4 > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_8_In_Page_7_Detail_Panel_Data: (policyNo) => `#section-policy-detail-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div:nth-child(3) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-8 > div > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_8_In_Page_8_Detail_Panel: (policyNo) => `#section-policy-detail-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div:nth-child(4) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-4 > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_8_In_Page_9_Detail_Panel_Data: (policyNo) => `#section-policy-detail-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div:nth-child(4) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-8 > div > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_8_In_Page_10_Detail_Panel: (policyNo) => `#section-policy-detail-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div:nth-child(5) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-4 > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_8_In_Page_11_Detail_Panel_Data: (policyNo) => `#section-policy-detail-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div:nth-child(5) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-8 > div > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_8_In_Page_12_Detail_Panel: (policyNo) => `#section-policy-detail-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div:nth-child(6) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-4 > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_8_In_Page_13_Detail_Panel_Data: (policyNo) => `#section-policy-detail-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div:nth-child(6) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-8 > div > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_8_In_Page_14_Detail_Panel: (policyNo) => `#section-policy-detail-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div:nth-child(7) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-4 > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_8_In_Page_15_Detail_Panel_Data: (policyNo) => `#section-policy-detail-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div:nth-child(7) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-8 > div > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_8_In_Page_16_Detail_Panel: (policyNo) => `#section-policy-detail-${policyNo} > div >div.MuiCollapse-container.MuiCollapse-entered >div >div > div > div> div > :nth-child(3) > :nth-child(1) > :nth-child(1) > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_8_In_Page_17_Detail_Panel_Data: (policyNo) => `#section-policy-detail-${policyNo} > div >div.MuiCollapse-container.MuiCollapse-entered >div >div > div > div> div > :nth-child(3) > :nth-child(1) > :nth-child(2) > div > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_8_In_Page_18_Detail_Panel: (policyNo) => `#section-policy-detail-${policyNo} > div >div.MuiCollapse-container.MuiCollapse-entered >div >div > div > div> div > :nth-child(3) > :nth-child(2) > :nth-child(1) > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_8_In_Page_19_Detail_Panel_Data: (policyNo) => `#section-policy-detail-${policyNo} > div >div.MuiCollapse-container.MuiCollapse-entered >div >div > div > div> div > :nth-child(3) > :nth-child(2) > :nth-child(2) > div > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_8_In_Page_20_Detail_Panel: (policyNo) => `#section-policy-detail-${policyNo} > div >div.MuiCollapse-container.MuiCollapse-entered >div >div > div > div> div > :nth-child(3) > :nth-child(3) > :nth-child(1) > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_8_In_Page_21_Detail_Panel_Data: (policyNo) => `#section-policy-detail-${policyNo} > div >div.MuiCollapse-container.MuiCollapse-entered >div >div > div > div> div > :nth-child(3) > :nth-child(3) > :nth-child(2) > div > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_8_In_Page_22_Detail_Panel: (policyNo) => `#section-policy-detail-${policyNo} > div >div.MuiCollapse-container.MuiCollapse-entered >div >div > div > div> div > :nth-child(3) > :nth-child(4) > :nth-child(1) > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_8_In_Page_23_Detail_Panel_Data: (policyNo) => `#section-policy-detail-${policyNo} > div >div.MuiCollapse-container.MuiCollapse-entered >div >div > div > div> div > :nth-child(3) > :nth-child(4) > :nth-child(2) > div > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_8_In_Page_24_Detail_Panel: (policyNo) => `#section-policy-detail-${policyNo} > div >div.MuiCollapse-container.MuiCollapse-entered >div >div > div > div> div > :nth-child(3) > :nth-child(5) > :nth-child(1) > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_8_In_Page_25_Detail_Panel_Data: (policyNo) => `#section-policy-detail-${policyNo} > div >div.MuiCollapse-container.MuiCollapse-entered >div >div > div > div> div > :nth-child(3) > :nth-child(5) > :nth-child(2) > div > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_8_In_Page_26_Detail_Panel: (policyNo) => `#section-policy-detail-${policyNo} > div >div.MuiCollapse-container.MuiCollapse-entered >div >div > div > div> div > :nth-child(3) > :nth-child(6) > :nth-child(1) > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_8_In_Page_27_Detail_Panel_Data: (policyNo) => `#section-policy-detail-${policyNo} > div >div.MuiCollapse-container.MuiCollapse-entered >div >div > div > div> div > :nth-child(3) > :nth-child(6) > :nth-child(2) > div > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_8_In_Page_28_Detail_Panel: (policyNo) => `#section-policy-detail-${policyNo} > div >div.MuiCollapse-container.MuiCollapse-entered >div >div > div > div> div > :nth-child(3) > :nth-child(7) > :nth-child(1) > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_8_In_Page_29_Detail_Panel_Data: (policyNo) => `#section-policy-detail-${policyNo} > div >div.MuiCollapse-container.MuiCollapse-entered >div >div > div > div> div > :nth-child(3) > :nth-child(7) > :nth-child(2) > div > p`,

  // CIS หน้าจอค้นหาข้อมูลลูกค้า > ดูรายละเอียด > panel ข้อมูลส่วนตัวผู้เอาประกัน
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_9_In_Page_1_Header_Panel: (policyNo) => `#section-policy-customer-${policyNo} > div > div.MuiButtonBase-root.MuiExpansionPanelSummary-root.makeStyles-root-48.uncollapsible.Mui-expanded > div > div > div.MuiGrid-root.ExpansionPanelSummaryTitle.MuiGrid-item`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_9_In_Page_2_Detail_Panel: (policyNo) => `#section-policy-customer-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div:nth-child(1) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-4 > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_9_In_Page_3_Detail_Panel_Data: (policyNo) => `#section-policy-customer-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div:nth-child(1) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-8 > div > div > div:nth-child(2) > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_9_In_Page_4_Detail_Panel: (policyNo) => `#section-policy-customer-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div:nth-child(2) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-4 > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_9_In_Page_5_Detail_Panel_Data: (policyNo) => `#section-policy-customer-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div:nth-child(2) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-8 > div > div > div:nth-child(2) > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_9_In_Page_6_Detail_Panel: (policyNo) => `#section-policy-customer-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div:nth-child(3) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-4 > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_9_In_Page_7_Detail_Panel_Data: (policyNo) => `#section-policy-customer-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div:nth-child(3) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-8 > div > div > div:nth-child(1) > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_9_In_Page_8_Detail_Panel: (policyNo) => `#section-policy-customer-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div:nth-child(4) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-4 > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_9_In_Page_9_Detail_Panel_Data: (policyNo) => `#section-policy-customer-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div:nth-child(4) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-8 > div > div > div > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_9_In_Page_10_Detail_Panel: (policyNo) => `#section-policy-customer-${policyNo} > div > div:nth-child(2) > div > div >div > div > div > div:nth-child(3) > div:nth-child(1) > div > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_9_In_Page_11_Detail_Panel_Data: (policyNo) => `#section-policy-customer-${policyNo} > div > div:nth-child(2) > div > div >div > div > div > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_9_In_Page_12_Detail_Panel: (policyNo) => `#section-policy-customer-${policyNo} > div > div:nth-child(2) > div > div >div > div > div > div:nth-child(3) > div:nth-child(2) > div > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_9_In_Page_13_Detail_Panel_Data: (policyNo) => `#section-policy-customer-${policyNo} > div > div:nth-child(2) > div > div >div > div > div > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > div > p`,

  // CIS หน้าจอค้นหาข้อมูลลูกค้า > ดูรายละเอียด > panel ข้อมูลตัวแทน (panel_10)
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_10_In_Page_1_Header_Panel: (policyNo) => `#tab${policyNo} > div:nth-child(3) > div.MuiButtonBase-root.MuiExpansionPanelSummary-root.makeStyles-root-48.uncollapsible.Mui-expanded > div > div > div.MuiGrid-root.ExpansionPanelSummaryTitle.MuiGrid-item`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_10_In_Page_2_Detail_Panel: (policyNo) => `#tab${policyNo} > div:nth-child(3) > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div:nth-child(1) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-4 > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_10_In_Page_3_Detail_Panel_Data: (policyNo) => `#tab${policyNo} > div:nth-child(3) > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div:nth-child(1) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-8 > div > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_10_In_Page_4_Detail_Panel: (policyNo) => `#tab${policyNo} > div:nth-child(3) > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div:nth-child(2) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-4 > div > div:nth-child(2) > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_10_In_Page_5_Detail_Panel_Data: (policyNo) => `#tab${policyNo} > div:nth-child(3) > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(2) > div:nth-child(2) > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-8 > div > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_10_In_Page_6_Detail_Panel: (policyNo) => `#tab${policyNo} > div:nth-child(3) > div:nth-child(2) > div > div > div > div > div > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_10_In_Page_7_Detail_Panel_Data: (policyNo) => `#tab${policyNo} > div:nth-child(3) > div:nth-child(2) > div > div > div > div > div > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_10_In_Page_8_Detail_Panel: (policyNo) => `#tab${policyNo} > div:nth-child(3) > div:nth-child(2) > div > div > div > div > div > div:nth-child(3) > div:nth-child(2) > div:nth-child(1) > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_10_In_Page_9_Detail_Panel_Data: (policyNo) => `#tab${policyNo} > div:nth-child(3) > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div:nth-child(3) > div:nth-child(2) > div:nth-child(2) > div > p`,

  // CIS หน้าจอค้นหาข้อมูลลูกค้า > ดูรายละเอียด > panel ข้อมูลติดต่อ (panel_11)
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_11_In_Page_1_Header_Panel: (policyNo) => `#tab${policyNo} > div:nth-child(5) > div.MuiButtonBase-root.MuiExpansionPanelSummary-root.makeStyles-root-48.uncollapsible.Mui-expanded > div > div > div.MuiGrid-root.ExpansionPanelSummaryTitle.MuiGrid-item`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_11_In_Page_2_Detail_Panel: (policyNo) => `#tab${policyNo} > div:nth-child(5) > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(1) > span > div`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_11_In_Page_3_Detail_Panel_Data: `#MUIDataTableBodyRow-0 > td:nth-child(2) > div > div:nth-child(1) > div > div:nth-child(2) > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_11_In_Page_4_Detail_Panel: (policyNo) => `#tab${policyNo} > div:nth-child(5) > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(2) > span > div`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_11_In_Page_5_Detail_Panel_Data: `#MUIDataTableBodyRow-0 > td:nth-child(4) > div > div > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_11_In_Page_6_Detail_Panel: (policyNo) => `#tab${policyNo} > div:nth-child(5) > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(3) > span > div`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_11_In_Page_7_Detail_Panel_Data: `#MUIDataTableBodyRow-0 > td:nth-child(6)`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_11_In_Page_8_Detail_Panel: (policyNo) => `#tab${policyNo} > div:nth-child(5) > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(4) > span > div`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_11_In_Page_9_Detail_Panel_Data: `#MUIDataTableBodyRow-0 > td:nth-child(8)`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_11_In_Page_10_Detail_Panel: (policyNo) => `#tab${policyNo} > div:nth-child(5) > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(5) > span > div`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_11_In_Page_11_Detail_Panel_Data: `#MUIDataTableBodyRow-0 > td:nth-child(10) > div > div:nth-child(1) > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_11_In_Page_12_Detail_Panel: (policyNo) => `#tab${policyNo} > div:nth-child(5) > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(6) > span > div`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_11_In_Page_13_Detail_Panel_Data: `#MUIDataTableBodyRow-0 > td:nth-child(12)`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_11_In_Page_14_Detail_Panel: (policyNo) => `#tab${policyNo} > div:nth-child(5) > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(7) > span > div`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_11_In_Page_15_Detail_Panel_Data: `#MUIDataTableBodyRow-0 > td:nth-child(14)`,

  // CIS หน้าจอค้นหาข้อมูลลูกค้า > ดูรายละเอียด > panel ผู้รับผลประโยชน์ (panel_12)
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_12_In_Page_1_Header_Panel: (policyNo) => `#section-beneficiary-${policyNo} > div > div.MuiButtonBase-root.MuiExpansionPanelSummary-root.makeStyles-root-48.uncollapsible.Mui-expanded > div > div > div.MuiGrid-root.ExpansionPanelSummaryTitle.MuiGrid-item`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_12_In_Page_2_Detail_Panel: (policyNo) => `#section-beneficiary-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(1) > span > div`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_12_In_Page_3_Detail_Panel_Data: `#MUIDataTableBodyRow-0 > td:nth-child(2)`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_12_In_Page_4_Detail_Panel: (policyNo) => `#section-beneficiary-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(2) > span > div`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_12_In_Page_5_Detail_Panel_Data: `#MUIDataTableBodyRow-0 > td:nth-child(4)`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_12_In_Page_6_Detail_Panel: (policyNo) => `#section-beneficiary-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(3) > span > div`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_12_In_Page_7_Detail_Panel_Data: `#MUIDataTableBodyRow-0 > td:nth-child(6) > div > div:nth-child(2) > p`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_12_In_Page_8_Detail_Panel: (policyNo) => `#section-beneficiary-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(4) > span > div`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_12_In_Page_9_Detail_Panel_Data: `#MUIDataTableBodyRow-0 > td:nth-child(8)`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_12_In_Page_10_Detail_Panel: (policyNo) => `#section-beneficiary-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(5) > span > div`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_12_In_Page_11_Detail_Panel_Data: `#MUIDataTableBodyRow-0 > td:nth-child(10)`,

  // CIS หน้าจอค้นหาข้อมูลลูกค้า > ดูรายละเอียด > panel บัญชีธนาคาร/บัญชีพร้อมเพย์ (panel_13)
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_13_In_Page_1_Header_Panel: (policyNo) => `#section-bank-account-${policyNo} > div > div.MuiButtonBase-root.MuiExpansionPanelSummary-root.makeStyles-root-48.uncollapsible.Mui-expanded > div > div > div.MuiGrid-root.ExpansionPanelSummaryTitle.MuiGrid-item`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_13_In_Page_2_Detail_Panel: (policyNo) => `#section-bank-account-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-true > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(1) > span > div`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_13_In_Page_3_Detail_Panel_Data: `#MUIDataTableBodyRow-0 > td:nth-child(2)`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_13_In_Page_4_Detail_Panel: (policyNo) => `#section-bank-account-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-true > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(2) > span > div`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_13_In_Page_5_Detail_Panel_Data: `#MUIDataTableBodyRow-0 > td:nth-child(4)`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_13_In_Page_6_Detail_Panel: (policyNo) => `#section-bank-account-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-true > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(3) > span > div`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_13_In_Page_7_Detail_Panel_Data: `#MUIDataTableBodyRow-0 > td:nth-child(6) > div > span`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_13_In_Page_8_Detail_Panel: (policyNo) => `#section-bank-account-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-true > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(4) > span > div`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_13_In_Page_9_Detail_Panel_Data: `#MUIDataTableBodyRow-0 > td:nth-child(8)`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_13_In_Page_10_Detail_Panel: (policyNo) => `#section-bank-account-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-true > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(5) > span > div`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_13_In_Page_11_Detail_Panel_Data: `#MUIDataTableBodyRow-0 > td:nth-child(10)`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_13_In_Page_12_Detail_Panel: (policyNo) => `#section-bank-account-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-true > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(6) > span > div`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_13_In_Page_13_Detail_Panel_Data: `#MUIDataTableBodyRow-0 > td:nth-child(12)`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_13_In_Page_14_Detail_Panel: (policyNo) => `#section-bank-account-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-true > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(7) > span > div`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_13_In_Page_15_Detail_Panel_Data: `#MUIDataTableBodyRow-0 > td:nth-child(14)`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_13_In_Page_16_Detail_Panel: (policyNo) => `#section-bank-account-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-true > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(8) > span > div`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_13_In_Page_17_Detail_Panel_Data: `#MUIDataTableBodyRow-0 > td:nth-child(16)`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_13_In_Page_18_Detail_Panel: (policyNo) => `#section-bank-account-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-true > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(9) > span > div`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_13_In_Page_19_Detail_Panel_Data: `#MUIDataTableBodyRow-0 > td:nth-child(18)`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_13_In_Page_20_Detail_Panel: (policyNo) => `#section-bank-account-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-true > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(10) > span > div`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_13_In_Page_21_Detail_Panel_Data: `#MUIDataTableBodyRow-0 > td:nth-child(20)`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_13_In_Page_22_Detail_Panel: (policyNo) => `#section-bank-account-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-true > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(11) > span > div`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_13_In_Page_23_Detail_Panel_Data: `#MUIDataTableBodyRow-0 > td:nth-child(22)`,

  // CIS หน้าจอค้นหาข้อมูลลูกค้า > ดูรายละเอียด > panel ประวัติการชำระเบี้ย (panel_14)
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_14_In_Page_1_Header_Panel: (policyNo) => `#section-payment-history-${policyNo} > div > div.MuiButtonBase-root.MuiExpansionPanelSummary-root.makeStyles-root-48.uncollapsible.Mui-expanded > div > div > div.MuiGrid-root.ExpansionPanelSummaryTitle.MuiGrid-item`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_14_In_Page_2_Detail_Panel: (policyNo) => `#section-payment-history-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(1) > span > div`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_14_In_Page_3_Detail_Panel_Data: `#MUIDataTableBodyRow-0 > td:nth-child(2)`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_14_In_Page_4_Detail_Panel: (policyNo) => `#section-payment-history-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(2) > span > div`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_14_In_Page_5_Detail_Panel_Data: `#MUIDataTableBodyRow-0 > td:nth-child(4)`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_14_In_Page_6_Detail_Panel: (policyNo) => `#section-payment-history-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(3) > span > div`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_14_In_Page_7_Detail_Panel_Data: `#MUIDataTableBodyRow-0 > td:nth-child(6)`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_14_In_Page_8_Detail_Panel: (policyNo) => `#section-payment-history-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(4) > span > div`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_14_In_Page_9_Detail_Panel_Data: `#MUIDataTableBodyRow-0 > td:nth-child(8)`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_14_In_Page_10_Detail_Panel: (policyNo) => `#section-payment-history-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(5) > span > div`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_14_In_Page_11_Detail_Panel_Data: `#MUIDataTableBodyRow-0 > td:nth-child(10)`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_14_In_Page_12_Detail_Panel: (policyNo) => `#section-payment-history-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(6) > span > div`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_14_In_Page_13_Detail_Panel_Data: `#MUIDataTableBodyRow-0 > td:nth-child(12)`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_14_In_Page_14_Detail_Panel: (policyNo) => `#section-payment-history-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(7) > span > div`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_14_In_Page_15_Detail_Panel_Data: `#MUIDataTableBodyRow-0 > td:nth-child(14)`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_14_In_Page_16_Detail_Panel: (policyNo) => `#section-payment-history-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(8) > span > div`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_14_In_Page_17_Detail_Panel_Data: `#MUIDataTableBodyRow-0 > td:nth-child(16)`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_14_In_Page_18_Detail_Panel: (policyNo) => `#section-payment-history-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(9) > span > div`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_14_In_Page_19_Detail_Panel_Data: `#MUIDataTableBodyRow-0 > td:nth-child(18)`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_14_In_Page_20_Detail_Panel: (policyNo) => `#section-payment-history-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(10) > span > div`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_14_In_Page_21_Detail_Panel_Data: `#MUIDataTableBodyRow-0 > td:nth-child(20)`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_14_In_Page_22_Detail_Panel: (policyNo) => `#section-payment-history-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(11) > span > div`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_14_In_Page_23_Detail_Panel_Data: `#MUIDataTableBodyRow-0 > td:nth-child(22)`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_14_In_Page_24_Detail_Panel: (policyNo) => `#section-payment-history-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(12) > span > div`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_14_In_Page_25_Detail_Panel_Data: `#MUIDataTableBodyRow-0 > td:nth-child(24)`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_14_In_Page_26_Detail_Panel: (policyNo) => `#section-payment-history-${policyNo} > div > div.MuiCollapse-container.MuiCollapse-entered > div > div > div > div > div > div > div > div.MUIDataTable-responsiveScroll-4 > table > thead > tr > th:nth-child(13) > span > div`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_14_In_Page_27_Detail_Panel_Data: `#MUIDataTableBodyRow-0 > td:nth-child(26)`,
  SELECTOR_CIS_MENU_SUB_1_SEARCH_1_Detail_1_panel_14_In_Page_28_Button: (policyNo) => `#section-payment-history-${policyNo} > div > div.MuiButtonBase-root.MuiExpansionPanelSummary-root.makeStyles-root-48.uncollapsible.Mui-expanded > div > div > div.MuiGrid-root.MuiGrid-item.MuiGrid-grid-xs-true > div > div > button > span.MuiButton-label`,
  
};